### ISSUE TITLE
Change how events are stored and displayed

### ISSUE THREAD

**Issue by 19th** [gdgriga/gdgriga.github.io#2]
Now events are stored in files events-upcoming.json and events-archive.json, but we need to store them in single file events.json and display them in UI blocks separating by event date.

Events upcoming should have events which are newer that today and old events should be older than today.

Additionally events should be provided by some kind of "EventsProvider", which will take events from file or from Firebase.

We need this because Firebase store events in single path "events", so to be consistent we will use same logic in both types of data fetching.

**Comment by skibish** [comment]
@19th I'm thinking about flattening JSON structure (like Zapier is doing) from

``` json
{
    "venue": {
      "name": "Scandiweb Office",
      "lat": 56.9648733,
      "lon": 24.1310773,
      "address": "9 Aristida Briāna iela",
      "city": "Riga",
      "country": "Latvia"
    }
}
```

to 

``` json
{
      "venue__address_1" : "214 Brivibas st.",
      "venue__city" : "Riga",
      "venue__country" : "lv",
      "venue__id" : "22974332",
      "venue__lat" : "56.970982",
      "venue__localized_country_name" : "Latvia",
      "venue__lon" : "24.160431",
      "venue__name" : "Accenture Latvia"
}
```

What do you think about it?

**Comment by 19th** [comment]
@skibish, yeah cool! Definitely do it.
We need to have one structure of events data, to be flexible to what source to use.

**Comment by skibish** [comment]
If #5 looks good, I will merge and close this issue @19th

**Comment by 19th** [comment]
Yeah, feel free to merge whenever you are ready, PR looks good.
The only thing left I think is "tool" commands. It will be nice to have them ready as fallback from firebase.
