### ISSUE TITLE
Add ability to fetch events from Firebase

### ISSUE THREAD

**Issue by 19th** [gdgriga/gdgriga.github.io#3]
Example of how to fetch data from firebase is here https://jsbin.com/jotatesoyi/1/edit?html,js,output

**Comment by 19th** [comment]
@skibish please check #6 and please create index for field "time" in Firebase, otherwise client works improperly and shows following warning:
`FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "time" at /events-upcoming to your security rules for better performance`

**Comment by skibish** [comment]
@19th I will add it now, branch merged, closing this issue
