### ISSUE TITLE
Add landing page block

### ISSUE THREAD

**Issue by 19th** [gdgriga/gdgriga.github.io#4]
On top of page we need to add block with background pictures from meetups and with numbers animation. Possible numbers - event, people count.

**Comment by 19th** [comment]
Found few libs to choose from.
Sorted by most liked descending :)

http://github.hubspot.com/odometer/docs/welcome/
https://inorganik.github.io/countUp.js/
https://www.npmjs.com/package/react-animated-number

**Comment by skibish** [comment]
I think we can give a try for first one (odometer). Looks good and it can be used natively. I think we could try to pair it with react :)
